pr: none
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - day5/apps/nodejs/textanalytics/*
      - day5/apps/infrastructure/templates/scm-textanalytics-nodejs-common.json
      - day5/apps/infrastructure/templates/scm-textanalytics-nodejs-infra.json
      - day5/apps/pipelines/cd-scm-textanalytics.yaml

variables:
  azureSubscription: AzureDeveloperCollege

stages:
  - stage: Build
    displayName: Build

    jobs:
      - template: jobs/build-scm-ta-func.yaml
        parameters:
          artifactDropName: drop

  - stage: Development
    displayName: Development
    dependsOn: Build

    jobs:
      - template: jobs/deploy-scm-ta-func.yaml
        parameters:
          name: Deploy Scm Textanalytics
          variablesFile: ../variables/cd-scm-textanalytics-dev.yaml
          variableGroupName: Day5-VariableGroup
          environmentName: ADC-DAY5-SCM-DEV
          azureSubscription: $(azureSubscription)
          artifactDropName: drop

  - stage: Test
    displayName: Test
    dependsOn: Development
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    jobs:
      - template: jobs/deploy-scm-ta-func.yaml
        parameters:
          name: Deploy Scm Textanalytics
          variablesFile: ../variables/cd-scm-textanalytics-test.yaml
          variableGroupName: Day5-VariableGroup
          environmentName: ADC-DAY5-SCM-TEST
          azureSubscription: $(azureSubscription)
          artifactDropName: drop
