pr: none
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - day5/apps/dotnetcore/Scm/*
      - day5/apps/infrastructure/templates/scm-api-dotnetcore.json
      - day5/apps/pipelines/cd-scm.yaml

variables:
  configuration: release
  azureSubscription: AzureDeveloperCollege
  containerRegistry: ADC-ContainerRegistry

stages:
  - stage: Build
    displayName: Build

    jobs:
      - template: jobs/build-scm-api.yaml
        parameters:
          configuration: $(configuration)
          artifactDropName: drop
          buildNumber: $(Build.BuildNumber)
          containerRegistryServiceConnection: $(containerRegistry)

  - stage: Development
    displayName: Development
    dependsOn: Build

    jobs:
      - template: jobs/deploy-scm-api.yaml
        parameters:
          name: Deploy Scm Api
          variablesFile: ../variables/cd-scm-dev.yaml
          variableGroupName: Day5-VariableGroup
          aadVariableGroupName: Day5-AAD-Dev
          environmentName: ADC-DAY5-SCM-DEV
          azureSubscription: $(azureSubscription)
          artifactDropName: drop

  - stage: Test
    displayName: Test
    dependsOn: Development
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

    jobs:
      - template: jobs/deploy-scm-api.yaml
        parameters:
          name: Deploy Scm Api
          variablesFile: ../variables/cd-scm-test.yaml
          variableGroupName: Day5-VariableGroup
          aadVariableGroupName: Day5-AAD-Test
          environmentName: ADC-DAY5-SCM-TEST
          azureSubscription: $(azureSubscription)
          artifactDropName: drop
