GET https://login.microsoftonline.com/b26f693d-3f41-4f90-b67c-69b1ea396820/oauth2/v2.0/authorize
?client_id=1246f209-3083-4f75-a9ab-1eaec388e957
&response_type=id_token+token
&redirect_uri=http://localhost:5001/api/tokenechofragment
&response_mode=fragment
&scope=openid profile http://scmapi-anmock-dev/Contacts.Read http://scmapi-anmock-dev/Contacts.Create http://scmapi-anmock-dev/Contacts.Update http://scmapi-anmock-dev/Contacts.Delete http://scmapi-anmock-dev/VisitReports.Read http://scmapi-anmock-dev/VisitReports.Create http://scmapi-anmock-dev/VisitReports.Update http://scmapi-anmock-dev/VisitReports.Delete
&nonce=1234

curl --request GET \
  --url 'https://login.microsoftonline.com/b26f693d-3f41-4f90-b67c-69b1ea396820/oauth2/v2.0/authorize?client_id=1246f209-3083-4f75-a9ab-1eaec388e957&response_type=id_token%20token&redirect_uri=http%3A%2F%2Flocalhost%3A5001%2Fapi%2Ftokenechofragment&response_mode=fragment&scope=openid%20profile%20http%3A%2F%2Fscmapi-anmock-dev%2FContacts.Read%20http%3A%2F%2Fscmapi-anmock-dev%2FContacts.Create%20http%3A%2F%2Fscmapi-anmock-dev%2FContacts.Update%20http%3A%2F%2Fscmapi-anmock-dev%2FContacts.Delete%20http%3A%2F%2Fscmapi-anmock-dev%2FVisitReports.Read%20http%3A%2F%2Fscmapi-anmock-dev%2FVisitReports.Create%20http%3A%2F%2Fscmapi-anmock-dev%2FVisitReports.Update%20http%3A%2F%2Fscmapi-anmock-dev%2FVisitReports.Delete&nonce=1234'
###
GET https://login.microsoftonline.com/b26f693d-3f41-4f90-b67c-69b1ea396820/oauth2/v2.0/authorize
?client_id=190015a8-85b6-487f-896c-1b517294031f
&response_type=id_token+token
&redirect_uri=http://localhost:5001/api/tokenechofragment
&response_mode=fragment
&scope=openid profile http://scmapi-anmock-test/Contacts.Read http://scmapi-anmock-test/Contacts.Create http://scmapi-anmock-test/Contacts.Update http://scmapi-anmock-test/Contacts.Delete http://scmapi-anmock-test/VisitReports.Read http://scmapi-anmock-test/VisitReports.Create http://scmapi-anmock-test/VisitReports.Update http://scmapi-anmock-test/VisitReports.Delete
&nonce=1234

curl --request GET \
  --url 'https://login.microsoftonline.com/b26f693d-3f41-4f90-b67c-69b1ea396820/oauth2/v2.0/authorize?client_id=190015a8-85b6-487f-896c-1b517294031f&response_type=id_token%20token&redirect_uri=http%3A%2F%2Flocalhost%3A5001%2Fapi%2Ftokenechofragment&response_mode=fragment&scope=openid%20profile%20http%3A%2F%2Fscmapi-anmock-test%2FContacts.Read%20http%3A%2F%2Fscmapi-anmock-test%2FContacts.Create%20http%3A%2F%2Fscmapi-anmock-test%2FContacts.Update%20http%3A%2F%2Fscmapi-anmock-test%2FContacts.Delete%20http%3A%2F%2Fscmapi-anmock-test%2FVisitReports.Read%20http%3A%2F%2Fscmapi-anmock-test%2FVisitReports.Create%20http%3A%2F%2Fscmapi-anmock-test%2FVisitReports.Update%20http%3A%2F%2Fscmapi-anmock-test%2FVisitReports.Delete&nonce=1234'

https://login.microsoftonline.com/b26f693d-3f41-4f90-b67c-69b1ea396820/oauth2/v2.0/authorize?response_type=id_token&scope=http%3A%2F%2Fscmapi-anmock-dev%2FContacts.Read%20http%3A%2F%2Fscmapi-anmock-dev%2FContacts.Create%20http%3A%2F%2Fscmapi-anmock-dev%2FContacts.Update%20http%3A%2F%2Fscmapi-anmock-dev%2FContacts.Delete%20http%3A%2F%2Fscmapi-anmock-dev%2FVisitReports.Read%20http%3A%2F%2Fscmapi-anmock-dev%2FVisitReports.Create%20http%3A%2F%2Fscmapi-anmock-dev%2FVisitReports.Update%20http%3A%2F%2Fscmapi-anmock-dev%2FVisitReports.Create%20openid%20profile&client_id=1246f209-3083-4f75-a9ab-1eaec388e957&redirect_uri=https%3A%2F%2Fanmockday4scmfedev.z20.web.core.windows.net%2Fcontacts&state=0dabc58d-4001-46b4-8908-72f87aacb244&nonce=8af4fe98-7590-4894-b5be-f26c79934561&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.2.0&client-request-id=3964a5d4-281d-4a46-b81a-a7ab5a714b0b&response_mode=fragment