Development:
UI AppId: 7426337e-67c5-4d16-b556-179eeaa025ce
API AppId: 57dc890b-4fb6-410d-9992-1a0c0dfadc84

Testing:
UI AppId: bcdc3d75-d470-4b93-8004-d0fa6b29c912
API AppId: 945fd0ff-6af9-46f9-abf1-6f6bca6e2d04

https://login.microsoftonline.com/2a151364-d43b-4192-b727-ab106e85ccdd/oauth2/v2.0/authorize?
client_id=7426337e-67c5-4d16-b556-179eeaa025ce
&response_type=id_token+token
&redirect_uri=http%3A%2F%2Flocalhost%3A5001%2Fapi%2Ftokenechofragment
&response_mode=fragment
&scope=openid%20profile%20http%3A%2F%2Fscmapi-dev%2FContacts.Read%20http%3A%2F%2Fscmapi-dev%2FContacts.Create%20http%3A%2F%2Fscmapi-dev%2FContacts.Update%20http%3A%2F%2Fscmapi-dev%2FContacts.Delete%20http%3A%2F%2Fscmapi-dev%2FVisitReports.Create%20http%3A%2F%2Fscmapi-dev%2FVisitReports.Update%20http%3A%2F%2Fscmapi-dev%2FVisitReports.Update%20http%3A%2F%2Fscmapi-dev%2FVisitReports.Delete
&nonce=1234
