GET https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize
?client_id=APPLICATION_ID
&response_type=id_token
&redirect_uri=http://localhost:5001/api/tokenecho
&response_mode=form_post
&scope=openid%20profile
&nonce=1234

