FROM node:12-alpine
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN apk update && \
    apk add wget && \
    wget https://github.com/dapr/dapr/releases/download/v0.5.0/daprd_linux_amd64.tar.gz && \
    tar -zxvf daprd_linux_amd64.tar.gz 
EXPOSE 5006
USER appuser
CMD ["sh", "runserver.sh", "subscribernodejs", "5006", "3500", "50000"]