pr: none
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - day2/apps/dotnetcore/*
      - day2/apps/infrastructure/templates/scm-api-dotnetcore.json
      - day2/apps/pipelines/cd-scm.yaml

variables:
  configuration: release
  azureSubscription: ANMOCK-InternalSubscription

stages:
  - stage: Build
    displayName: Build

    jobs:
      - job: Build
        displayName: Build Scm Api
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: ../dotnetcore/build/scm-api.yaml
            parameters:
              buildConfiguration: '$(configuration)'
          - task: CopyFiles@2
            inputs:
              sourceFolder: day2/apps/infrastructure/templates
              contents: |
                scm-api-dotnetcore.json
              targetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifactName: drop

  - stage: Development
    displayName: Deploy Scm to Development Stage
    dependsOn: Build

    jobs:
      - template: jobs/deploy-scm-api.yaml
        parameters:
          name: Deploy Scm Api
          variablesFile: ../variables/cd-scm-dev.yaml
          environmentName: ADC-DAY2-SCM-DEV
          azureSubscription: $(azureSubscription)

