parameters:
  artifactDropName: drop
  buildNumber: ""
  containerRegistryServiceConnection: ""

jobs:
  - job: Build
    displayName: Build Scm Frontend
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: ../../frontend/build/scm-fe.yaml
        parameters:
          buildNumber: ${{ parameters.buildNumber }}
          publishDockerImage: true
          containerRegistryServiceConnection: ${{ parameters.containerRegistryServiceConnection }}
      - task: CopyFiles@2
        inputs:
          SourceFolder: "day3/apps/frontend/scmfe/dist"
          Contents: "**"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/dist"
      - task: CopyFiles@2
        inputs:
          sourceFolder: day3/apps/infrastructure/templates
          contents: |
            scm-fe.json
          targetFolder: $(Build.ArtifactStagingDirectory)/templates
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifactName: ${{ parameters.artifactDropName }}
